SELECT MAX(CopiesSold) FROM STUDIES;

SELECT MIN(CourseFee) FROM STUDIES;

SELECT MAX(TIMESTAMPDIFF(YEAR, DateOfBirth, CURDATE())) FROM PROGRAMMER WHERE Gender = 'Male';

SELECT AVG(TIMESTAMPDIFF(YEAR, DateOfBirth, CURDATE())) FROM PROGRAMMER WHERE Gender = 'Female';

SELECT Name, TIMESTAMPDIFF(YEAR, JoiningDate, CURDATE()) AS Experience FROM PROGRAMMER ORDER BY Experience DESC;

SELECT COUNT(*) FROM STUDIES WHERE Course = 'PGDCA';

SELECT SUM(SellingCost * CopiesSold) FROM STUDIES WHERE SoftwareID IN (SELECT SoftwareID FROM SOFTWARE WHERE Language = 'C');

SELECT COUNT(*) FROM PROGRAMMER WHERE Institute = 'Sabhari';

SELECT COUNT(*) FROM SOFTWARE WHERE Language = 'dBase';

SELECT COUNT(*) FROM PROGRAMMER WHERE Institute = 'Pragathi';

SELECT COUNT(*) FROM STUDIES WHERE CourseFee BETWEEN 5000 AND 10000;

SELECT COUNT(*) FROM (SELECT DISTINCT ProgrammerID FROM STUDIES WHERE Course IN ('COBOL', 'Pascal')) AS T;

SELECT COUNT(*) FROM (SELECT DISTINCT ProgrammerID FROM STUDIES WHERE Course IN ('COBOL', 'Pascal')) AS T;

SELECT AVG(Salary) FROM PROGRAMMER;

SELECT COUNT(*) FROM PROGRAMMER WHERE Salary BETWEEN 2000 AND 4000;

SELECT Language, Name, SUM(SellingCost * CopiesSold) AS SalesCost FROM STUDIES JOIN SOFTWARE ON STUDIES.SoftwareID = SOFTWARE.SoftwareID JOIN PROGRAMMER ON STUDIES.ProgrammerID = PROGRAMMER.ProgrammerID GROUP BY Language, Name;


SELECT * FROM SOFTWARE WHERE DeveloperID IN (SELECT ProgrammerID FROM PROGRAMMER WHERE Institute = 'Sabhari' AND Gender = 'Male');


SELECT Name, TIMESTAMPDIFF(YEAR, DateOfBirth, CURDATE()) AS Age FROM PROGRAMMER WHERE Gender = 'Female' AND JoiningDate <= '1992-12-31' ORDER BY Age DESC LIMIT 1;

SELECT Name, TIMESTAMPDIFF(YEAR, DateOfBirth, CURDATE()) AS Age FROM PROGRAMMER WHERE Gender = 'Male' AND DateOfBirth >= '1965-01-01' AND DateOfBirth <= '1965-12-31' ORDER BY Age ASC LIMIT 1;

SELECT * FROM STUDIES WHERE SellingCost = (SELECT MIN(SellingCost) FROM STUDIES);

SELECT Name FROM PROGRAMMER WHERE Gender = 'Female' AND Salary > 3000 AND ProgrammerID NOT IN (SELECT ProgrammerID FROM STUDIES WHERE Course IN ('C', 'C++', 'Oracle', 'dBase'));

SELECT Name, TIMESTAMPDIFF(YEAR, DateOfBirth, CURDATE()) AS Age FROM PROGRAMMER WHERE ProgrammerID IN (SELECT ProgrammerID FROM STUDIES WHERE Course = 'dBase') ORDER BY Age ASC LIMIT 1;

SELECT Language FROM SOFTWARE GROUP BY Language HAVING COUNT(*) = 1;

SELECT Name, TIMESTAMPDIFF(YEAR, JoiningDate, CURDATE()) AS Experience FROM PROGRAMMER WHERE Gender = 'Male' AND ProgrammerID IN (SELECT ProgrammerID FROM STUDIES WHERE Course = 'Pascal') ORDER BY Experience DESC LIMIT 1;

SELECT Language, COUNT(*) AS NumPackages FROM SOFTWARE WHERE DevelopmentCost < 1000 GROUP BY Language;

SELECT MAX(Salary) AS HighestSalary, MIN(Salary) AS LowestSalary, AVG(Salary) AS AverageSalary FROM PROGRAMMER WHERE Salary > 2000;

